apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-webapp
  namespace: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-webapp
  template:
    metadata:
      labels:
        app: chatbot-webapp
    spec:
      imagePullSecrets:
      - name: gitlab-regcred
      containers:
      - name: chatbot-webapp
        image: 192.168.0.100:5050/homelab/signature_project:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: webapp-secret
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 20
      tolerations:
      - key: "key"
        operator: "Equal"
        value: "value"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ubuntu-2
