apiVersion: v1
kind: Service
metadata:
  name: chatbot-webapp-service
  namespace: chatbot
spec:
  selector:
    app: chatbot-webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
