apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-nginx
  namespace: chatbot
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
