apiVersion: v1
kind: Service
metadata:
  name: chatbot-nginx-service
  namespace: chatbot
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30082
  type: NodePort
