"""Recreating migrations after sync

Revision ID: 7272f166af1f
Revises: 
Create Date: 2025-03-21 00:01:31.815581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7272f166af1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('idproject', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idproject'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('iduser', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('iduser'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chat',
    sa.Column('idchat', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['chatbot_schema.project.idproject'], ),
    sa.ForeignKeyConstraint(['user_id'], ['chatbot_schema.user.iduser'], ),
    sa.PrimaryKeyConstraint('idchat')
    )
    op.create_table('message',
    sa.Column('idmessage', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=10), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chatbot_schema.chat.idchat'], ),
    sa.PrimaryKeyConstraint('idmessage')
    )
    op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkey')
    )
    op.drop_table('message')
    op.drop_table('chat')
    op.drop_table('user')
    op.drop_table('project')
    # ### end Alembic commands ###
