"""Clean initial schema

Revision ID: fd25dee971a9
Revises: 
Create Date: 2025-03-26 11:53:52.426789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd25dee971a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('idappuser', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idappuser'),
    sa.UniqueConstraint('username'),
    schema='chatbot_schema'
    )
    op.create_table('project',
    sa.Column('idproject', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idproject'),
    sa.UniqueConstraint('name'),
    schema='chatbot_schema'
    )
    op.create_table('chat',
    sa.Column('idchat', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['chatbot_schema.project.idproject'], ),
    sa.ForeignKeyConstraint(['user_id'], ['chatbot_schema.app_user.idappuser'], ),
    sa.PrimaryKeyConstraint('idchat'),
    schema='chatbot_schema'
    )
    op.create_table('message',
    sa.Column('idmessage', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=10), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chatbot_schema.chat.idchat'], ),
    sa.PrimaryKeyConstraint('idmessage'),
    schema='chatbot_schema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    op.drop_table('message', schema='chatbot_schema')
    op.drop_table('chat', schema='chatbot_schema')
    op.drop_table('project', schema='chatbot_schema')
    op.drop_table('app_user', schema='chatbot_schema')
    # ### end Alembic commands ###
