apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@192.168.0.100:homelab/signature_project.git'
    path: manifests/base
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: chatbot
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 3
