apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: chatbot
data:
  nginx.conf: |
    events {}

    http {
        server {
            listen 80;

            location / {
                proxy_pass http://chatbot-webapp-service.chatbot.svc.cluster.local:80;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }
    }
